# Generated by Django 4.0.3 on 2022-06-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMenu', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_usuario',
            old_name='cargo',
            new_name='tipo',
        ),
    ]
